---
# Deployment 部署 Spring Boot 应用程序
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
#          image: docker.io/wwweeeiii/java-web-demo:relese-v1.0.0   # 替换为您的 Spring Boot 应用程序的 Docker 镜像
          image: wwweeeiii/java-web-demo:relese-v1.0.0   # 替换为您的 Spring Boot 应用程序的 Docker 镜像
          ports:
            - containerPort: 8888   # 替换为您的 Spring Boot 应用程序监听的端口
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/dbname   # 替换为您的 MySQL 数据库的连接 URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials   # 替换为存储 MySQL 用户名和密码的 Kubernetes Secret 名称
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials   # 替换为存储 MySQL 用户名和密码的 Kubernetes Secret 名称
                  key: password

---
# Service 暴露 Spring Boot 应用程序
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30009   # 替换为您的 Spring Boot 应用程序的监听端口
  type: NodePort

---
# Deployment 部署 MySQL 数据库
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:latest   # 替换为您所需的 MySQL 版本
          ports:
            - containerPort: 3306   # MySQL 默认端口
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials   # 替换为存储 MySQL 用户名和密码的 Kubernetes Secret 名称
                  key: password

---
# Service 暴露 MySQL 数据库
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      protocol: TCP
#      targetPort: 30006
  type: ClusterIP

---
# Kubernetes Secret 存储 MySQL 用户名和密码
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  username: cm9vdA==   # 替换为经过 Base64 编码的 MySQL 用户名
  password: cm9vdA==  # 替换为经过 Base64 编码的 MySQL 密码